#!/bin/bash

. config.sh
. functions.sh

if [ -z "$1" ]
then
  echo "Usage: destroy <snapshot name>"
  exit 1
fi

if [ "$1" == "master" ]
then
  echo "The master database may not be destroyed."
  exit 1
fi

snapshot_exists "/dev/$VG/$1"
check_user
destroy $1
