#!/bin/bash

if [ ! -L $0 ]
then
  export LMM_ROOT="$(cd "$(dirname "$0")" && pwd)"
else
  export LMM_ROOT="$(dirname "$(readlink -f "$0")")"
fi

if [ -z "$1" ]
then
  COMMANDS=`ls $LMM_ROOT/commands | sed ':a;N;$!ba;s/\n/ | /g'`
  echo "Usage: lmm [ $COMMANDS ]"
  exit 1
fi

$LMM_ROOT/commands/$*
