#!/bin/bash

. config.sh
. functions.sh

if [ -z "$1" ]
then
  echo "Usage: switch <snapshot name>"
  exit 1
fi

snapshot_exists "/dev/$VG/$1"
check_user

snapshot_active $1
if [ $? -eq 0 ]
then
  echo "$1 is already the currently active database."
  exit 1
fi

switch $1
