#!/bin/bash

. $LMM_ROOT/config.sh
. $LMM_ROOT/functions.sh

if [ -z "$1" ]
then
  echo "Usage: branch [-d] <snapshot name>"
  exit 1
fi

# Support git style branch -d.
if [ "$1" == "-d" ]
then
  $LMM_ROOT/commands/delete $2
  exit
fi

snapshot_available "/dev/$VG/mysql-$1"
check_user
branch $1
