#!/bin/bash

. $LMM_ROOT/config.sh
. $LMM_ROOT/functions.sh

if [ -z "$1" ]
then
  echo "Usage: checkout <snapshot name>"
  exit 1
fi

snapshot_exists "/dev/$VG/mysql-$1"
check_user

snapshot_active $1
if [ $? -eq 0 ]
then
  echo "$1 is the currently active database."
  exit 1
fi

checkout $1
