#!/bin/bash

. $LMM_ROOT/config.sh
. $LMM_ROOT/functions.sh

if [ -z "$1" ]
then
  echo "Usage: destroy <snapshot name>"
  exit 1
fi

if [ "$1" == "master" ]
then
  echo "The master database may not be destroyed."
  exit 1
fi

snapshot_exists "/dev/$VG/$1"

snapshot_active $1
if [ $? -eq 0 ]
then
  echo "The active snapshot $1 can not be destroyed."
  exit 1
fi

check_user

read -p "Are you sure you want to DESTROY $1 (y/n)? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  destroy $1
fi
