#!/bin/bash

. $LMM_ROOT/config.sh
. $LMM_ROOT/functions.sh

check_user

echo "Active snapshot:" $(echo $(active) | sed "s/\/mysql\///")

echo ""

echo "Database snapshots:"
lvs -o lv_name --noheadings | grep -v thinpool

free
